config/routes.rb
Rails.application.routes.draw do
  root 'expenses#index'
  
  resources :expenses, only: [:index]

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  has_many :expenses
end

app/models/expense.rb
# == Schema Information
#
# Table name: expenses
#
#  id          :integer          not null, primary key
#  category_id :integer
#  date        :date
#  concept     :string
#  amount      :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Expense < ActiveRecord::Base
  belongs_to :category  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/expenses_controller.rb
# == Schema Information
#
# Table name: expenses
#
#  id          :integer          not null, primary key
#  category_id :integer
#  date        :date
#  concept     :string
#  amount      :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class ExpensesController < ApplicationController
  def index
    if params[:concept].present? && params[:category_id].present?
      @expenses = Expense.where("concept LIKE ? AND category_id = ?", "%#{params[:concept]}%",params[:category_id]).order("date DESC")
    elsif params[:concept].present? && !params[:category_id].present?
      @expenses = Expense.where("concept LIKE ?", "%#{params[:concept]}%").order("date DESC")
    elsif !params[:concept].present? && params[:category_id].present?
      @expenses = Expense.where("category_id = ?", params[:category_id]).order("date DESC")
    else
      @expenses = Expense.order("date DESC")
    end     
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
# == Schema Information
#
# Table name: expenses
#
#  id          :integer          not null, primary key
#  category_id :integer
#  date        :date
#  concept     :string
#  amount      :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

module ExpensesHelper
end

app/views/expenses/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <%= form_tag expenses_path, method: :get do %>
        <div class="form-group">
          <%= text_field_tag :concept, params[:concept], class: "form-control", placeholder: "Concepto" %>
        </div>
        <div class="form-group">
          <%= select_tag :category_id, options_from_collection_for_select(Category.all, "id", "name", params[:category_id]), prompt: "Categoría", class: "form-control" %>
        </div>
        <%= submit_tag "Buscar", name: nil, class: "btn btn-primary btn-md" %>
      <% end %>
    </div>
    <div class="col-sm-9">
      <table class="table" id="transactions">
        <thead>
          <tr>
            <th>Fecha</th>
            <th>Concepto</th>
            <th class="text-right">Categoría</th>
            <th class="text-right">Monto</th>
          </tr>
        </thead>
        <tbody>
          <% @expenses.each do |expense| %>
            <tr>
              <td class="date">
                <div class="day"><%= l(expense.date, format: "%d") %></div>
                <div class="month"><%= l(expense.date, format: "%b") %></div>
              </td>
              <td class="concept"><%= expense.concept %></td>
              <td class="category text-right"><%= expense.category.name %></td>
              <td class="text-right amount" style="width: 170px;"><%= number_to_currency(expense.amount, precision: 0) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xpenses</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-static-top navbar-inverse">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">mis<strong>finanzas</strong></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Gastos <span class="sr-only">(current)</span></a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

<%= yield %>

</body>
</html>